### ISSUE TITLE
DragTouchListActivity侧滑数组越界

### ISSUE THREAD

**Issue by sheilazxx** [yanzhenjie/SwipeRecyclerView#101]
` FATAL EXCEPTION: main
                                                                                        Process: com.yanzhenjie.recyclerview.swipe.sample, PID: 3678
                                                                                        java.lang.ArrayIndexOutOfBoundsException: length=13; index=-1
                                                                                            at android.support.v4.util.SparseArrayCompat.keyAt(SparseArrayCompat.java:240)
                                                                                            at com.yanzhenjie.recyclerview.swipe.SwipeAdapterWrapper.getItemViewType(SwipeAdapterWrapper.java:88)
                                                                                            at com.yanzhenjie.recyclerview.swipe.widget.DefaultItemDecoration.drawHorizontal(DefaultItemDecoration.java:164)
                                                                                            at com.yanzhenjie.recyclerview.swipe.widget.DefaultItemDecoration.onDraw(DefaultItemDecoration.java:154)
                                                                                            at android.support.v7.widget.RecyclerView.onDraw(RecyclerView.java:3934)
                                                                                            at android.view.View.draw(View.java:17071)
                                                                                            at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3869)
                                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16053)
                                                                                            at android.view.View.draw(View.java:16837)
                                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                                            at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1230)
                                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                                            at android.view.View.draw(View.java:17074)
                                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16053)
                                                                                            at android.view.View.draw(View.java:16837)
                                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16048)
                                                                                            at android.view.View.draw(View.java:16837)
                                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16048)
                                                                                            at android.view.View.draw(View.java:16837)
                                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16048)
                                                                                            at android.view.View.draw(View.java:16837)
                                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16048)
                                                                                            at android.view.View.draw(View.java:16837)
                                                                                            at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                                                            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                                                            at android.view.View.draw(View.java:17074)
                                                                                            at com.android.internal.policy.DecorView.draw(DecorView.java:751)
                                                                                            at android.view.View.updateDisplayListIfDirty(View.java:16053)
                                                                                            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:656)
                                                                                            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:662)
                                                                                            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:770)
                                                                                            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2796)
                                                                                            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2604)
                                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2211)
                                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
                                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
                                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                                            at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)`

**Comment by yanzhenjie** [comment]
谢谢反馈，是demo的问题，已修复。
