### ISSUE TITLE
ListItem的侧滑删除，角标问题

### ISSUE THREAD

**Issue by behindeye** [yanzhenjie/SwipeRecyclerView#104]
>  java.lang.ArrayIndexOutOfBoundsException: length=13; index=-1
                                                                                          at android.support.v4.util.SparseArrayCompat.keyAt(SparseArrayCompat.java:240)
                                                                                          at com.yanzhenjie.recyclerview.swipe.SwipeAdapterWrapper.getItemViewType(SwipeAdapterWrapper.java:88)
                                                                                          at com.yanzhenjie.recyclerview.swipe.widget.DefaultItemDecoration.drawHorizontal(DefaultItemDecoration.java:164)
                                                                                          at com.yanzhenjie.recyclerview.swipe.widget.DefaultItemDecoration.onDraw(DefaultItemDecoration.java:154)
                                                                                          at android.support.v7.widget.RecyclerView.onDraw(RecyclerView.java:3934)
                                                                                          at android.view.View.draw(View.java:17232)
                                                                                          at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3869)
                                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16197)
                                                                                          at android.view.View.draw(View.java:16998)
                                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                                          at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1230)
                                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                                          at android.view.View.draw(View.java:17235)
                                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16197)
                                                                                          at android.view.View.draw(View.java:16998)
                                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16192)
                                                                                          at android.view.View.draw(View.java:16998)
                                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16192)
                                                                                          at android.view.View.draw(View.java:16998)
                                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16192)
                                                                                          at android.view.View.draw(View.java:16998)
                                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16192)
                                                                                          at android.view.View.draw(View.java:16998)
                                                                                          at android.view.ViewGroup.drawChild(ViewGroup.java:3777)
                                                                                          at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3560)
                                                                                          at android.view.View.draw(View.java:17235)
                                                                                          at com.android.internal.policy.DecorView.draw(DecorView.java:801)
                                                                                          at android.view.View.updateDisplayListIfDirty(View.java:16197)
                                                                                          at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:676)
                                                                                          at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:682)
                                                                                          at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:796)
                                                                                          at android.view.ViewRootImpl.draw(ViewRootImpl.java:2989)
                                                                                          at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2783)
                                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2374)
                                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1364)
                                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6757)
                                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:923)
                                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:735)
                                                                                          at android.view.Choreographer.doFrame(Choreographer.java:667)
                                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:909)
                                                                                          at android.os.Handler.handleCallback(Handler.java:755)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                          at android.os.Looper.loop(Looper.java:156)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by chencha218** [comment]
哥们这个问题解决了吗

**Comment by yanzhenjie** [comment]
暂时可以使用notifyDataSetChanged代替。

**Comment by yanzhenjie** [comment]
新版已经修改，欢迎更新使用。
