### ISSUE TITLE
我在两个Fragment中使用同一个布局，然后使用replace不断切换这个两个Fragment，几次之后就crash了

### ISSUE THREAD

**Issue by saisaixv** [yanzhenjie/SwipeRecyclerView#129]
java.lang.IllegalStateException: Observer com.yanzhenjie.recyclerview.swipe.SwipeMenuRecyclerView$2@c40f609 was not registered.
                                                                           at android.database.Observable.unregisterObserver(Observable.java:69)
                                                                           at android.support.v7.widget.RecyclerView$Adapter.unregisterAdapterDataObserver(RecyclerView.java:6583)
                                                                           at com.yanzhenjie.recyclerview.swipe.SwipeMenuRecyclerView.onDetachedFromWindow(SwipeMenuRecyclerView.java:331)
                                                                           at android.view.View.dispatchDetachedFromWindow(View.java:15454)

**Comment by yanzhenjie** [comment]
了解了，你暂时用1.1.3-fixed这个版本会不会有这个问题了。

**Comment by saisaixv** [comment]
用1.1.3-fixed这个版本没有出现切换几次后crash的问题
