### ISSUE TITLE
BaseRecyclerViewAdapterHelper类转化异常

### ISSUE THREAD

**Issue by shuaimango** [yanzhenjie/SwipeRecyclerView#131]
java.lang.ClassCastException: com.yanzhenjie.recyclerview.swipe.SwipeAdapterWrapper cannot be cast to com.chad.library.adapter.base.BaseQuickAdapter
                      at com.chad.library.adapter.base.listener.SimpleClickListener.onInterceptTouchEvent(SimpleClickListener.java:45)
                      at android.support.v7.widget.RecyclerView.dispatchOnItemTouchIntercept(RecyclerView.java:2628)
                      at android.support.v7.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:2674)
                      at com.yanzhenjie.recyclerview.swipe.SwipeMenuRecyclerView.onInterceptTouchEvent(SwipeMenuRecyclerView.java:517)

**Comment by shuaimango** [comment]
列表页使用了BaseRecyclerViewAdapterHelper，一点击列表item就出现如上异常

**Comment by yanzhenjie** [comment]
这个不是`SwipeRecyclerView`这边转化异常，你需要`instance of`。  
在`SwipeRecyclerView`中拿到原始`Adapter`：`SwipeRecyclerView#getOriginAdapter();`

**Comment by shuaimango** [comment]
getOriginAdapter()之后怎么做呢   列表数据能正常展示，一触碰列表item就抛异常

**Comment by yanzhenjie** [comment]
这就是你最开始set的adapter。

**Comment by shuaimango** [comment]
那最终还是要写OriginAdapter  用不了BaseRecyclerViewAdapterHelper？

**Comment by shuaimango** [comment]
麻烦写个应用BaseRecyclerViewAdapterHelper的demo    非常感谢

**Comment by yanzhenjie** [comment]
我没用过你说的那个`Adapter`，你设置给`RecyclerView`的`Adapter`会被`SwipeMenuRecyclerView`替换掉并且做一个包裹，所以直接从`RecyclerView#getAdapter()`到的`Adapter`已经不是你最开始设置的那个`Adapter`了。可以用上面说的方法拿到本身设置的`Adapter`。

**Comment by liangtian123** [comment]
我也是碰到这个问题，那这样说这两个库不能同时用了，或者得把BaseRecyclerViewAdapterHelper库导进项目修改
