### ISSUE TITLE
使用BaseRecyclerViewAdapterHelper的DataBinding 报错

### ISSUE THREAD

**Issue by EthanCo** [yanzhenjie/SwipeRecyclerView#140]
使用BaseRecyclerViewAdapterHelper的DataBinding的形式，getTag的时候获取ViewDataBinding为null  

```
public class BindingViewHolder extends BaseViewHolder {

        public BindingViewHolder(View view) {
            super(view);
        }

        public ViewDataBinding getBinding() {
            //此处获取为null
            return (ViewDataBinding) itemView.getTag(R.id.BaseQuickAdapter_databinding_support);
        }
    }
```

具体的代码在这里，把以下代码注释，运行正常。把以下代码取消注释，就会报错。

```
mSwipeRecyclerView.setSwipeMenuCreator({ leftMenu, rightMenu, viewType ->
            val deleteItem = SwipeMenuItem(activity)
            deleteItem.text = "Hello"
            deleteItem.setImage(R.drawable.scene_delete)
            //...; // 各种文字和图标属性设置。
            leftMenu.addMenuItem(deleteItem); // 在Item左侧添加一个菜单。
        })
```

报错信息如下

'
java.lang.NullPointerException:  
 Attempt to invoke virtual method 'boolean android.databinding.ViewDataBinding.setVariable(int, java.lang.Object)' on a null object reference
                                                                   at com.lib.frame.view.encapsulation.brvah.binding.BrvahItemBinding.bind(BrvahItemBinding.java:58)
                                                                   at com.lib.frame.view.encapsulation.brvah.binding.BaseItemBindingAdapter.convert(BaseItemBindingAdapter.java:28)
                                                                   at com.lib.frame.view.encapsulation.brvah.binding.BaseItemBindingAdapter.convert(BaseItemBindingAdapter.java:15)
                                                                   at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:927)
                                                                   at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:68)
                                                                   at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6482)
                                                                   at com.yanzhenjie.recyclerview.swipe.SwipeAdapterWrapper.onBindViewHolder(SwipeAdapterWrapper.java:182)
                                                                   at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6515)
                                                                   at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5458)
                                                                   at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5724)
                                                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5563)
                                                                   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5559)
                                                                   at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2229)
                                                                   at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1556)
                                                                   at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1516)
                                                                   at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:608)
                                                                   at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
                                                                   at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3410)
                                                                   at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3962)
                                                                   at android.view.View.layout(View.java:18071)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5724)
                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
                                                                   at android.view.View.layout(View.java:18071)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5724)
                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
                                                                   at android.view.View.layout(View.java:18071)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5724)
                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
                                                                   at android.view.View.layout(View.java:18071)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5724)
                                                                   at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:132)
                                                                   at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                   at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
                                                                   at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:869)
                                                                   at android.view.View.layout(View.java:18071)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5724)
                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
                                                                   at android.view.View.layout(View.java:18071)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5724)
                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
                                                                   at android.view.View.layout(View.java:18071)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5724)
                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
                                                                   at android.view.View.layout(View.java:18071)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5724)
                                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1982)
                                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1826)
                                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1735)
                                                                   at android.view.View.layout(View.java:18071)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5724)
                                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:383)
                                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:321)
                                                                   at com.android.internal.policy.DecorView.onLayout(DecorView.java:752)
                                                                   at android.view.View.layout(View.java:18071)
                                                                   at android.view.ViewGroup.layout(ViewGroup.java:5724)
                                                                   at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2748)
                                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2413)
                                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1496)
                                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7131)
                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:912)
                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:714)
                                                                   at android.view.Choreographer.doFrame(Choreographer.java:648)
                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:898)
                                                                   at android.os.Handler.handleCallback(Handler.java:836)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                   at android.os.Looper.loop(Looper.java:203)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6475)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1134)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
`

**Comment by yanzhenjie** [comment]
内部会把你的`ViewHolder`的`ItemView`替换掉，如果是1.1.3版本你可以这样做：
```java
View realItemView = ((ViewGroup)itemView.findViewById(R.id.swipe_content)).getChildAt(0);
```
