### ISSUE TITLE
 java.lang.IllegalStateException: Observer com.yanzhenjie.recyclerview.swipe.SwipeMenuRecyclerView$2@50752ff was not registered.

### ISSUE THREAD

**Issue by woshiqinwei** [yanzhenjie/SwipeRecyclerView#141]
我在PageAdapter.destroyItem的时候
 java.lang.IllegalStateException: Observer com.yanzhenjie.recyclerview.swipe.SwipeMenuRecyclerView$2@50752ff was not registered.
                                                                 at android.database.Observable.unregisterObserver(Observable.java:69)
                                                                 at android.support.v7.widget.RecyclerView$Adapter.unregisterAdapterDataObserver(RecyclerView.java:6627)
                                                                 at com.yanzhenjie.recyclerview.swipe.SwipeMenuRecyclerView.onDetachedFromWindow(SwipeMenuRecyclerView.java:331)
                                                                 at android.view.View.dispatchDetachedFromWindow(View.java:14599)
                                                                 at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3110)
                                                                 at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3102)
                                                                 at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3102)
                                                                 at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3102)
                                                                 at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3102)
                                                                 at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3102)
                                                                 at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4642)
                                                                 at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4615)
                                                                 at android.view.ViewGroup.removeView(ViewGroup.java:4546)
                                                                 at android.support.v4.view.ViewPager.removeView(ViewPager.java:1498)

**Comment by liulinru13** [comment]
我也遇到了同样的问题，是在list所在view调用了removeAllViews的方法的时候报出的异常，你解决了么？

**Comment by tianyuliuxing** [comment]
recyclerView嵌套SwipeMenuRecyclerView滑动出现   java.lang.IllegalStateException: Observer com.yanzhenjie.recyclerview.swipe.SwipeMenuRecyclerView$2@4aa7b9a0 was not registered.

**Comment by Addibro** [comment]
Hey thanks for quick response. I’m using 2.1.0 apparently. Should I switch to 1.2.0 instead or will that only break more stuff?

**Comment by yanzhenjie** [comment]
@Addibro Sorry, I am a bit confused, are you using SwipeMenuRecyclerView? The current version of SwipeMenuRecyclerView is 1.2.0, the previous version was 1.1.4, and the 2.x version has not been released yet.

**Comment by Addibro** [comment]
Sorry, I mixed up names with you and someone else. You can ignore this from now on.
