### ISSUE TITLE
在viewpager里面提示was not registered？

### ISSUE THREAD

**Issue by 1009256707** [yanzhenjie/SwipeRecyclerView#157]
viewpager有2个的情况不报错，3个的时候来回划过循环2次才报这个错误，求解决
java.lang.IllegalStateException: Observer com.yanzhenjie.recyclerview.swipe.SwipeMenuRecyclerView$2@1d815a7 was not registered.
                      at android.database.Observable.unregisterObserver(Observable.java:69)
                      at android.support.v7.widget.RecyclerView$Adapter.unregisterAdapterDataObserver(RecyclerView.java:6735)

**Comment by yanzhenjie** [comment]
升级到最新版。
