### ISSUE TITLE
初始化的时候报错

### ISSUE THREAD

**Issue by yuzhongrong** [yanzhenjie/SwipeRecyclerView#161]
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                                          Caused by: java.lang.IllegalStateException: Cannot set menu creator, setAdapter has already been called.
                                                                             at com.yanzhenjie.recyclerview.swipe.SwipeMenuRecyclerView.checkAdapterExist(SwipeMenuRecyclerView.java:201)
                                                                             at com.yanzhenjie.recyclerview.swipe.SwipeMenuRecyclerView.setSwipeMenuCreator(SwipeMenuRecyclerView.java:262)
                                                                             at com.shuweikeji.idcwallet2.ui.activity.notice.NoticeActivity.initView(NoticeActivity.java:163)
                                                                             at com.shuweikeji.idcwallet2.base.BaseActivity.onCreate(BaseActivity.java:105)

**Comment by yanzhenjie** [comment]
这里已经告诉你错误信息了：
```
Cannot set menu creator, setAdapter has already been called.
```

**Comment by ghost** [comment]
我全局就只有一个啊 怎么还报错呢

**Comment by threedeer** [comment]
他这个好像是菜单点击事件初始化了就会跟item的点击事件初始化冲突，看了下，底层menu点击好像就是item的点击

**Comment by threedeer** [comment]
刚才试了下
setOnItemClickListener放在OnItemMenuClickListener前面就行了
