### ISSUE TITLE
新问题,嵌套过程中出现的

### ISSUE THREAD

**Issue by lizhanqi** [yanzhenjie/SwipeRecyclerView#190]
java.lang.IllegalStateException: Observer com.yanzhenjie.recyclerview.swipe.SwipeMenuRecyclerView$2@992ab34 was not registered.
        at android.database.Observable.unregisterObserver(Observable.java:69)
        at android.support.v7.widget.RecyclerView$Adapter.unregisterAdapterDataObserver(RecyclerView.java:6971)
        at com.yanzhenjie.recyclerview.swipe.SwipeMenuRecyclerView.onDetachedFromWindow(SwipeMenuRecyclerView.java:331)
近期嵌套(通过添加headView)时候出现了这个异常,具体但是我适配器注册过后还是报错, 望指点迷津,谢谢

**Comment by lizhanqi** [comment]
问题解决了,这个问题在1.1.3版本有问题,1.1.4就好了具体原因不清楚,因为这个问题折腾了快两天了.深感惭愧
