### ISSUE TITLE
Scrapped or attached views may not be recycled. isScrap:false 

### ISSUE THREAD

**Issue by zengyaoliang** [yanzhenjie/SwipeRecyclerView#212]
2018-11-06 20:03:22.025 26818-26818/com.narwel.narwelrobots E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.narwel.narwelrobots, PID: 26818
    java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true com.narwel.narwelrobots.wiget.NarwelRecyclerView{361727a VFED..... .F....ID 0,0-1080,535 #7f0801c5 app:id/rv_clean_project}, adapter:com.yanzhenjie.recyclerview.swipe.SwipeAdapterWrapper@ce1c1c6, layout:android.support.v7.widget.LinearLayoutManager@a4e0587, context:com.narwel.narwelrobots.main.mvp.view.CleaningActivity@ce1e7f0
        at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:6053)
        at android.support.v7.widget.RecyclerView$Recycler.quickRecycleScrapView(RecyclerView.java:6166)
        at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleScrapInt(RecyclerView.java:8859)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3885)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3540)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:19685)
        at android.view.ViewGroup.layout(ViewGroup.java:6077)
        at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:606)
        at android.view.View.layout(View.java:19685)
        at android.view.ViewGroup.layout(ViewGroup.java:6077)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19685)
        at android.view.ViewGroup.layout(ViewGroup.java:6077)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19685)
        at android.view.ViewGroup.layout(ViewGroup.java:6077)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:19685)
        at android.view.ViewGroup.layout(ViewGroup.java:6077)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19685)
        at android.view.ViewGroup.layout(ViewGroup.java:6077)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19685)
        at android.view.ViewGroup.layout(ViewGroup.java:6077)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19685)
        at android.view.ViewGroup.layout(ViewGroup.java:6077)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19685)
        at android.view.ViewGroup.layout(ViewGroup.java:6077)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:764)
        at android.view.View.layout(View.java:19685)
        at android.view.ViewGroup.layout(ViewGroup.java:6077)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2535)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2251)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1431)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6861)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1026)
        at android.view.Choreographer.doCallbacks(Choreographer.java:838)
        at android.view.Choreographer.doFrame(Choreographer.java:769)
2018-11-06 20:03:22.025 26818-26818/com.narwel.narwelrobots E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1012)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6648)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:818)
2018-11-06 20:03:22.038 26818-26818/com.narwel.narwelrobots E/CrashReport: Java Crash Happen cause by main(2)

**Comment by ZuJunJun** [comment]
> 2018-11-06 20:03:22.025 26818-26818/com.narwel.narwelrobots E/AndroidRuntime: FATAL EXCEPTION: main
> Process: com.narwel.narwelrobots, PID: 26818
> java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true com.narwel.narwelrobots.wiget.NarwelRecyclerView{361727a VFED..... .F....ID 0,0-1080,535 #7f0801c5 app:id/rv_clean_project}, adapter:com.yanzhenjie.recyclerview.swipe.SwipeAdapterWrapper@ce1c1c6, layout:android.support.v7.widget.LinearLayoutManager@a4e0587, context:com.narwel.narwelrobots.main.mvp.view.CleaningActivity@ce1e7f0
> at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:6053)
> at android.support.v7.widget.RecyclerView$Recycler.quickRecycleScrapView(RecyclerView.java:6166)
> at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleScrapInt(RecyclerView.java:8859)
> at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3885)
> at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3540)
> at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
> at android.view.View.layout(View.java:19685)
> at android.view.ViewGroup.layout(ViewGroup.java:6077)
> at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:606)
> at android.view.View.layout(View.java:19685)
> at android.view.ViewGroup.layout(ViewGroup.java:6077)
> at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
> at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
> at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
> at android.view.View.layout(View.java:19685)
> at android.view.ViewGroup.layout(ViewGroup.java:6077)
> at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
> at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
> at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
> at android.view.View.layout(View.java:19685)
> at android.view.ViewGroup.layout(ViewGroup.java:6077)
> at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
> at android.view.View.layout(View.java:19685)
> at android.view.ViewGroup.layout(ViewGroup.java:6077)
> at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
> at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
> at android.view.View.layout(View.java:19685)
> at android.view.ViewGroup.layout(ViewGroup.java:6077)
> at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
> at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
> at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
> at android.view.View.layout(View.java:19685)
> at android.view.ViewGroup.layout(ViewGroup.java:6077)
> at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
> at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
> at android.view.View.layout(View.java:19685)
> at android.view.ViewGroup.layout(ViewGroup.java:6077)
> at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
> at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
> at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
> at android.view.View.layout(View.java:19685)
> at android.view.ViewGroup.layout(ViewGroup.java:6077)
> at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
> at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
> at com.android.internal.policy.DecorView.onLayout(DecorView.java:764)
> at android.view.View.layout(View.java:19685)
> at android.view.ViewGroup.layout(ViewGroup.java:6077)
> at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2535)
> at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2251)
> at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1431)
> at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6861)
> at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1026)
> at android.view.Choreographer.doCallbacks(Choreographer.java:838)
> at android.view.Choreographer.doFrame(Choreographer.java:769)
> 2018-11-06 20:03:22.025 26818-26818/com.narwel.narwelrobots E/AndroidRuntime: at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1012)
> at android.os.Handler.handleCallback(Handler.java:790)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loop(Looper.java:164)
> at android.app.ActivityThread.main(ActivityThread.java:6648)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:818)
> 2018-11-06 20:03:22.038 26818-26818/com.narwel.narwelrobots E/CrashReport: Java Crash Happen cause by main(2)

我也碰到了这个问题，请问老哥怎么解决的？应该是我们自己代码问题，老哥能不能说说你的怎么回事，谢谢

**Comment by gs666** [comment]
不提前清空列表就好了
