### ISSUE TITLE
1.2版本出现混淆错误。debug版本没有问题，混淆后的就报错，log如下：

### ISSUE THREAD

**Issue by guiguzixiansheng** [yanzhenjie/SwipeRecyclerView#226]

**Comment by guiguzixiansheng** [comment]
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
        at android.support.v7.widget.RecyclerView$a.b(RecyclerView.java:6796)
        at android.support.v7.widget.RecyclerView$o.a(RecyclerView.java:5975)
        at android.support.v7.widget.RecyclerView$o.a(RecyclerView.java:5858)
        at android.support.v7.widget.RecyclerView$o.c(RecyclerView.java:5854)
        at android.support.v7.widget.LinearLayoutManager$c.a(LinearLayoutManager.java:2230)
        at android.support.v7.widget.LinearLayoutManager.a(LinearLayoutManager.java:1557)
        at android.support.v7.widget.LinearLayoutManager.a(LinearLayoutManager.java:1517)
        at android.support.v7.widget.LinearLayoutManager.c(LinearLayoutManager.java:612)
        at android.support.v7.widget.RecyclerView.N(RecyclerView.java:3924)
        at android.support.v7.widget.RecyclerView.q(RecyclerView.java:3641)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:19663)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:19663)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19663)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19663)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19663)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
        at android.view.View.layout(View.java:19663)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2500)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2216)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1396)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6773)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6501)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by yanzhenjie** [comment]
小哥下次提问时认真点。
你可能是禁用了三方自带的混淆，该库自带了混淆规则，如果无效你可以像旧版本一样手动添加：
```
-keepclasseswithmembers class android.support.v7.widget.RecyclerView$ViewHolder {
   public final View *;
}
```
