### ISSUE TITLE
还维护吗？遇到bug

### ISSUE THREAD

**Issue by OkamiyGit** [yanzhenjie/SwipeRecyclerView#320]
java.lang.NoSuchMethodError: No virtual method getBindingAdapterPosition()I in class Lcom/chad/library/adapter/base/viewholder/BaseViewHolder; or its super classes (declaration of 'com.chad.library.adapter.base.viewholder.BaseViewHolder' appears in /data/app/com.okamiy.nearly-DytZ2gjm4m1fpJV6Gctutw==/base.apk)
        at com.chad.library.adapter.base.BaseQuickAdapter.bindViewClickListener$lambda-7$lambda-6(BaseQuickAdapter.kt:495)
        at com.chad.library.adapter.base.BaseQuickAdapter.$r8$lambda$aqWf9Mix2Hshed6QsGcdRVGlHL8(Unknown Source:0)
        at com.chad.library.adapter.base.BaseQuickAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:7312)
        at android.view.View.performClickInternal(View.java:7286)
        at android.view.View.access$3600(View.java:838)
        at android.view.View$PerformClick.run(View.java:28242)
        at android.os.Handler.handleCallback(Handler.java:900)

**Comment by luqiming666** [comment]
请详细描述你的使用场景、调用方法。
