### ISSUE TITLE
fragment 内嵌 fragment，切换外部fragment，会报错

### ISSUE THREAD

**Issue by f987002856** [yanzhenjie/SwipeRecyclerView#92]
java.lang.IllegalStateException: Observer com.yanzhenjie.recyclerview.swipe.SwipeMenuRecyclerView$4@526f60a8 was not registered.
                                                                         at android.database.Observable.unregisterObserver(Observable.java:69)
                                                                         at android.support.v7.widget.RecyclerView$Adapter.unregisterAdapterDataObserver(RecyclerView.java:6581)
                                                                         at com.yanzhenjie.recyclerview.swipe.SwipeMenuRecyclerView.onDetachedFromWindow(SwipeMenuRecyclerView.java:297)
                                                                         at android.view.View.dispatchDetachedFromWindow(View.java:12160)
                                                                         at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2570)
                                                                         at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2568)
                                                                         at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2568)
                                                                         at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2568)
                                                                         at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2568)
                                                                         at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3788)
                                                                         at android.view.ViewGroup.removeViewInternal(ViewGroup.java:3761)
                                                                         at android.view.ViewGroup.removeView(ViewGroup.java:3693)
                                                                         at android.support.v4.view.ViewPager.removeView(ViewPager.java:1527)
                                                                         at com.jess.arms.base.AdapterViewPager.destroyItem(AdapterViewPager.java:64)
                                                                         at android.support.v4.view.ViewPager.populate(ViewPager.java:1202)
                                                                         at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
                                                                         at android.support.v4.view.ViewPager$3.run(ViewPager.java:273)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:562)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:531)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
                                                                         at android.os.Handler.handleCallback(Handler.java:730)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                         at android.os.Looper.loop(Looper.java:137)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:525)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                         at dalvik.system.NativeStart.main(Native Method)
08-24 19:29:25.558 8625-8625/? I/Process: Sending signal. PID: 8625 SIG: 9

**Comment by ZQ173** [comment]
严大，复现方法，在 fragment 里的 onCreateView 方法，改成如下：
        if (layout == null) {
            layout = inflater.inflate(R.layout.fragment_menu, container, false);
        }
        return layout;
