### ISSUE TITLE
删除Item,用notifyDataSetChanged正常,notifyItemRemoved这个就报错,数组越界的问题

### ISSUE THREAD

**Issue by cgfgfvmocking** [yanzhenjie/SwipeRecyclerView#95]
java.lang.ArrayIndexOutOfBoundsException: length=13; index=-1
                                                     at android.support.v4.util.SparseArrayCompat.keyAt(SparseArrayCompat.java:240)
                                                     at com.yanzhenjie.recyclerview.swipe.SwipeAdapterWrapper.getItemViewType(SwipeAdapterWrapper.java:88)
                                                     at com.yanzhenjie.recyclerview.swipe.widget.DefaultItemDecoration.drawHorizontal(DefaultItemDecoration.java:164)
                                                     at com.yanzhenjie.recyclerview.swipe.widget.DefaultItemDecoration.onDraw(DefaultItemDecoration.java:154)
                                                     at android.support.v7.widget.RecyclerView.onDraw(RecyclerView.java:4052)
                                                     at android.view.View.draw(View.java:17067)
                                                     at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3987)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:16049)
                                                     at android.view.View.draw(View.java:16833)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:16044)
                                                     at android.view.View.draw(View.java:16833)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                     at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1229)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:16044)
                                                     at android.view.View.draw(View.java:16833)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:16044)
                                                     at android.view.View.draw(View.java:16833)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:16044)
                                                     at android.view.View.draw(View.java:16833)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:16044)
                                                     at android.view.View.draw(View.java:16833)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:16044)
                                                     at android.view.View.draw(View.java:16833)
                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
                                                     at android.view.View.draw(View.java:17070)
                                                     at com.android.internal.policy.DecorView.draw(DecorView.java:751)
                                                     at android.view.View.updateDisplayListIfDirty(View.java:16049)
                                                     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:656)
                                                     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:662)
                                                     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:770)
                                                     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2796)
                                                     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2604)
                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2211)
                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by zhonghaojie** [comment]
兄弟你这个解决了吗

**Comment by wytskshu** [comment]
没有啊,听说1.1.1版本可以

**Comment by chencha218** [comment]
你好，请问这个问题解决了吗

**Comment by yanzhenjie** [comment]
是DeaultItemDecoration在删除Item时存在一个bug，现在已经修复。
